import { useEffect } from 'react'

/**
 * This is the base component to deal with MicroAd scripts and handle lifecycle.
 * Wrap this component by levarge the styled-components function [styling any component](https://styled-components.com/docs/basics#styling-any-component)
 * to maintain MicroAd's ad as separate component.
 * Check ~/components/ads/micro-ad/micro-ad-with-label.js for the example.
 * @param {Object} props
 * @param {string} props.unitId - MicroAd's unit id to connect to MicroAd's script and style
 * @param {string} [props.className] - styled-components property to set style for a React Component
 * @returns {React.ReactElement}
 */
export default function MicroAd({ unitId, className }) {
  useEffect(() => {
    const microAdScript = document.createElement('script')
    microAdScript.id = `compass-fit-script-${unitId}`
    microAdScript.async = true
    microAdScript.src =
      (document.location.protocol === 'https:' ? 'https://' : 'http://') +
      `nt.compass-fit.jp/lift_widget.js?adspot_id=${unitId}`
    document.head.appendChild(microAdScript)

    return () => {
      const microAdScript = document.querySelector(
        `#compass-fit-script-${unitId}`
      )
      microAdScript?.remove()

      // remove script instered from MicroAd
      const autoGeneratedScript = document.querySelector(
        `script[src*="${unitId}"`
      )
      autoGeneratedScript?.remove()

      // remove style inserted from MicroAd
      const microAdStyle = [...document.querySelectorAll('style')].find(
        (item) => item.textContent.includes(`#compass-fit-${unitId}`)
      )
      microAdStyle?.remove()
    }
  }, [unitId])
  return <div className={className} id={`compass-fit-${unitId}`} />
}
