const PROGRAMABLE_SEARCH_LIMIT_START = 91
const PROGRAMABLE_SEARCH_NUM = 10
const PROGRAMABLE_SEARCH_PER_PAGE = 36

export {
  PROGRAMABLE_SEARCH_LIMIT_START,
  PROGRAMABLE_SEARCH_NUM,
  PROGRAMABLE_SEARCH_PER_PAGE,
}
